### ISSUE TITLE
KaTeX UPDATE

### ISSUE THREAD

**Issue by xinyu-yang** [sunt-programator/CodeIT#168]
## KaTeX UPDATE

- Feature 1
  It seems that katex has a new update and supports some new features (e.g., align, align*). Do you have a plan to update this lib?

## Useful reference

https://github.com/KaTeX/KaTeX/releases/tag/v0.13.0

**Comment by victor-pogor** [comment]
Hi @xinyu-yang 

I was thinking about it. I looked in the code and I don't like that we need to update manually the libs and also update [this file](https://github.com/sunt-programator/CodeIT/blob/master/assets/lib/VERSION).

So, I read about [Include Dependencies In package.json / node_modules](https://gohugo.io/hugo-pipes/js/#include-dependencies-in-packagejson--node_modules). I'm thinking of including all libs in `package.json`. But we will not have the CDN option since at the output we will have a bundle file. Still investigating...

**Comment by xinyu-yang** [comment]
Hi @victor-pogor . Thank you for your patient answer.

Actually, I have tried the environment `aligned` with
```
\begin{aligned}
   a&=b+c \\
   d+e&=f
\end{aligned}
```
, which environment is supported by KaTeX v0.11.1 according to https://katex.org/docs/0.11.1/supported.html.  But I can not get the right rendering, while other one-line formula surrounded by $$ can get the right rendering.

Fortunately, I see this https://github.com/halogenica/beautifulhugo/issues/183, the solution is to replace `\\` with `\cr`, which is
```
\begin{aligned}
   a&=b+c \cr
   d+e&=f
\end{aligned}
```
 In this method, I will have to replace all the `\\` with `\cr` in my posts (though not much). I'm not sure if `\cr` is the right usage, but I think this usage is not compatible with mathjax and latex. 

So I just wonder if there is a method to make `\\`  work? Thank You!
