### ISSUE TITLE
[BUG] Theme Version Settings

### ISSUE THREAD

**Issue by ktw717** [sunt-programator/CodeIT#232]
## Describe the bug

When I try to set the theme using the latest release found [here](https://github.com/sunt-programator/CodeIT/releases) I see the latest is `0.1.2`

So of course I try to set my theme using this in the config

```
[params]
  # CodeIT theme version
  version = "0.1.2"
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
```

## Expected behavior

That it works and uses that version of the them.

## What Actually Happens

```
Start building sites … 
hugo v0.84.4+extended darwin/amd64 BuildDate=unknown
INFO 2021/07/03 21:34:33 syncing static files to /
ERROR 2021/07/03 21:34:33 Compatibility Error 兼容性错误

0.1.2 -> 0.2.X:
You have an incompatible update. See https://github.com/suntprogramator/CodeIT/releases
你进行了一次不兼容的更新. 参考 https://github.com/suntprogramator/CodeIT/releases
WARN 2021/07/03 21:34:33 

Current environment is "development". The "comment system", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "CDN" 和 "fingerprint" 不会启用.
Built in 143 ms
Error: Error building site: logged 1 error(s)
```

But this does work:
```
[params]
  # CodeIT theme version
  version = "0.2.X"
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
```
## Build Environment

- OS:`macos BigSur`
- Theme version/commit: `I am not sure due to this impacting this`
- Hugo version `hugo v0.84.4+extended darwin/amd64 BuildDate=unknown`

**Comment by victor-pogor** [comment]
Hi @ktw717,

The problem is that the version does not correspond in the `init.html` file:

https://github.com/sunt-programator/CodeIT/blob/d1fa3573eb1aaacd9f448b2e5053fc058aa1d72c/layouts/partials/init.html#L3-L11

With the version provided in the `config.toml` file.

https://github.com/sunt-programator/CodeIT/blob/d1fa3573eb1aaacd9f448b2e5053fc058aa1d72c/exampleSite/config.toml#L629-L631

The next version will be `v0.2.0` and the problem should disappear.
