### ISSUE TITLE
SGSS doesn't fingerprint external resources

### ISSUE THREAD

**Issue by jadmadi** [sunt-programator/CodeIT#98]
## Describe the bug
I enabled Fingerprint, but it's working on local resources only not the ones listed in data/cdn/jsdelivr.yml.

## Expected behavior
Expected output 
`<script src="https://cdn.jsdelivr.net/npm/twemoji@13.0.0/dist/twemoji.min.js" integrity="sha384-avLpk7eChiSgpDvwa4N7hvg9vj6V9sfFmGHurVkPOlWUalASzcO3d2x3qcbQqhsH" crossorigin="anonymous"></script>`

Current output

`<script type="c20bf019a833dc89b2a6e585-text/javascript" src=https://cdn.jsdelivr.net/npm/twemoji@13.0.0/dist/twemoji.min.js></script>`

## Build Environment
Debian 10.7
Theme commit - 838a74e
Hugo version 80.0/extended

**Comment by victor-pogor** [comment]
Hi @jadmadi.

I will take a look at this issue.

Thank you for contributing to this repo 😉

**Comment by sheldonhull** [comment]
I had to remove `sha256` from the config for the styles to load correctly. This was all styles for the site. Might need a new issue, but wanted to mention this in case it's related. Cheers

**Comment by jadmadi** [comment]
> Hi @jadmadi.
> 
> I will take a look at this issue.
> 
> Thank you for contributing to this repo wink
Awesome Thank you @victor-pogor I tried looking for the responsible code block but couldn't find it as I'm fairly new to Hugo.

**Comment by victor-pogor** [comment]
@jadmadi This I found in [one](https://github.com/sunt-programator/CodeIT/blob/master/assets/lib/algoliasearch/algoliasearch-lite.umd.min.js) of the minified local files. 
```
 * Skipped minification because the original files appears to be already minified.
 * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
```

It's relating specifically to the files from CDN because the minified content can change easily. For this, I think it will not be possible to assign the integrity to CDN files.

Relating to local files, Hugo calculates and assigns the integrity on the site-building process and the files will remain static till the next build.

@sheldonhull I tried to set the fingerprint and it works (even in production).

![Local script with the integrity attribute](https://user-images.githubusercontent.com/24962085/112206451-9f08e580-8c1e-11eb-9a9d-5206fb784e1f.png)

![The local script was loaded correctly](https://user-images.githubusercontent.com/24962085/112206551-bcd64a80-8c1e-11eb-8ce4-8936d57d8818.png)
